name: Python Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv pip install -r requirements.txt
        uv pip install pytest pytest-cov
        uv pip install -e .
        
    - name: Lint with Ruff
      run: |
        # Check with Ruff
        ruff check src/ app.py setup.py setup_api_key.py
        
    - name: Format check with Ruff
      run: |
        # Verify formatting with Ruff
        ruff format --check src/ app.py setup.py setup_api_key.py
        
    - name: Test with pytest
      run: |
        pytest --cov=src tests/